import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field, field_validator
from app.api.auth_dependencies import requires
from app.security import authz

from app.config import settings
from app.storage.human_review_repository import read_human_reviews

router = APIRouter()


def _read_json_file(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Required governance evidence file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


@router.get("/governance/report", dependencies=[Depends(requires(authz.PERM_VIEW_AUDIT_LOG, "governance_report"))])
def get_governance_report():
    import os

    from app.rules.manchester_engine import get_approved_ruleset
    from app.data_pipeline.mimic_full_loader import full_mimic_diagnostic
    from app.version import APP_VERSION, PACKAGE_CHECKPOINT

    ruleset = get_approved_ruleset()
    provisional_active = bool(ruleset) and ruleset.get(
        "validation_status"
    ) != "CLINICALLY_APPROVED"

    report_raw = os.environ.get("MIMIC_FULL_REPORT_DIR", "")
    report_dir = Path(report_raw).expanduser() if report_raw else settings.processed_dir
    schema_report_path = report_dir / "full_mimic_schema_report.json"
    comparison_path = report_dir / "full_mimic_model_comparison.json"
    model_card_path = report_dir / "mimic_full_model_card.json"
    dataset_card_path = report_dir / "mimic_full_dataset_card.json"
    from app.security.local_paths import credentialed_artifact_path
    human_review_path = credentialed_artifact_path(
        settings.processed_dir / "human_reviews.jsonl",
        purpose="human_review output",
    )

    human_reviews = read_human_reviews(human_review_path)
    reviewed_count = len(human_reviews)
    mimic_status = full_mimic_diagnostic()

    def _present(path: Path) -> Dict[str, Any]:
        return {
            "status": "PASS" if path.exists() else "NOT_AVAILABLE",
            "filename": path.name,
        }

    controls = {
        "full_mimic_runtime_configuration": {
            "status": "PASS" if mimic_status.get("full_mimic_loadable") else "NOT_CONFIGURED",
            "evidence": {
                "active_profile": mimic_status.get("active_profile"),
                "mimic_full_dir_env_set": mimic_status.get("mimic_full_dir_env_set"),
                "full_mimic_loadable": mimic_status.get("full_mimic_loadable"),
                "reason": mimic_status.get("reason"),
            },
        },
        "full_mimic_schema_report": {
            **_present(schema_report_path),
            "evidence": "Generated by ml_training/full_mimic/verify_schema.py on the approved environment.",
        },
        "full_mimic_model_comparison": {
            **_present(comparison_path),
            "evidence": "Generated by ml_training/full_mimic/compare_models.py on the approved environment.",
        },
        "full_mimic_model_card": {
            **_present(model_card_path),
            "evidence": "Aggregate model card only; no raw rows.",
        },
        "full_mimic_dataset_card": {
            **_present(dataset_card_path),
            "evidence": "Aggregate dataset card only; no raw rows.",
        },
        "triage_input_separation": {
            "status": "PASS",
            "evidence": {
                "policy": (
                    "Only triage-time fields enter serving/training features. "
                    "MIMIC acuity is a training/evaluation label only; disposition, "
                    "diagnoses, medrecon, pyxis, outtime, and repeated vitalsign "
                    "records are excluded from triage-time inputs."
                ),
            },
        },
        "human_review_audit_records": {
            "status": "PASS",
            "evidence": {"review_records": reviewed_count},
        },
        "official_manchester_mapping": {
            "status": "NOT_IMPLEMENTED",
            "evidence": (
                "No official Manchester Triage System mapping is implemented. "
                "Neither KTAS nor MIMIC-IV-ED is Manchester-labelled."
            ),
        },
        "provisional_mts_research_ruleset": {
            "status": "ACTIVE" if provisional_active else "DISABLED",
            "evidence": (
                {
                    "ruleset_id": ruleset.get("ruleset_id") if ruleset else None,
                    "is_official_mts": False,
                    "is_clinically_approved": False,
                    "note": (
                        "Provisional, unvalidated research ruleset is active "
                        "(default-on). Produces provisional Manchester-style "
                        "categories that are NOT the official MTS and NOT "
                        "clinically approved; clinician review required on every "
                        "output. See RULESET_PROVENANCE.md."
                    ),
                }
                if provisional_active
                else "Provisional MTS research ruleset is disabled; engine is fully gated."
            ),
        },
        "clinical_use_guardrail": {
            "status": "PASS",
            "evidence": "System declares not_for_clinical_use and requires human review.",
        },
    }
    blocking_issues: List[str] = [
        "No clinician-APPROVED Manchester triage ruleset configured "
        "(a provisional, unvalidated research ruleset is active by default, "
        "but it is not approved for clinical use)."
        if provisional_active
        else "No Manchester triage ruleset configured."
    ]
    if not schema_report_path.exists():
        blocking_issues.append("Full-MIMIC schema report has not been generated in this environment.")
    if not comparison_path.exists():
        blocking_issues.append("Full-MIMIC model-comparison metrics have not been generated in this environment.")

    return {
        "system_name": "AI Triage Agentic Workflow",
        "app_version": APP_VERSION,
        "package_checkpoint": PACKAGE_CHECKPOINT,
        "default_dataset": "MIMIC-IV-ED-Full-v2.2",
        "datasets_available": ["MIMIC-IV-ED-Full-v2.2"],
        "governance_evidence_dataset": "MIMIC-IV-ED-Full-v2.2",
        "clinical_use_status": "not_for_clinical_use",
        "provisional_mts_mode": "enabled" if provisional_active else "disabled",
        "official_mts_ruleset": False,
        "clinically_approved_ruleset": False,
        "governance_verdict": "RESEARCH_CHECKPOINT_NOT_CLINICAL_USE_READY",
        "blocking_issues": blocking_issues,
        "controls": controls,
        "responsible_ai_review_gate": {
            "intake": (
                "Default and only prediction dataset is full MIMIC-IV-ED v2.2 "
                "(credentialed), read from MIMIC_FULL_ED_DIR on an approved "
                "environment. Synthetic MIMIC-shaped fixtures are used only for "
                "tests and the Azure supervisor demo, never as a clinical or "
                "patient-data source."
            ),
            "scope": (
                "Workflow produces deterministic safety checks plus a full-MIMIC "
                "acuity model when MIMIC_FULL_MODEL_PATH is configured. The model "
                "predicts MIMIC/ESI acuity, which is rendered in a five-level "
                "display with an escalate-only vital override. Outputs are "
                "research-only and not clinically validated."
            ),
            "assess": "Full-MIMIC schema, model comparison, cards, leakage guard, and tests are the expected evidence.",
            "probe": "Human review records can be saved and retrieved.",
            "decide": (
                "System remains blocked from clinical use: any Manchester-style "
                "category shown is provisional and unvalidated, and clinician "
                "review is required on every output."
            ),
        },
    }


@router.post(
    "/governance/policy-checks",
    dependencies=[Depends(requires(authz.PERM_VIEW_AUDIT_LOG, "governance_policy_checks"))],
)
def run_governance_policy_checks():
    """Execute governance policy checks on the backend.

    Streamlit must not import/run the workflow orchestrator directly for
    protected actions. This route preserves the same executable checks while
    keeping workflow execution behind FastAPI auth/RBAC/audit.
    """
    from app.agents.orchestrator import run_workflow
    from app.governance.policy_checks import run_policy_checks, policy_red_team_probes

    return {
        "policy_results": run_policy_checks(run_workflow, settings),
        "red_team_results": policy_red_team_probes(),
        "scope": "backend_executed_policy_checks",
    }


class WandbLogRequest(BaseModel):
    policy_results: Dict[str, Any]
    red_team_results: Optional[Dict[str, Any]] = None
    model_metrics: Optional[Dict[str, Any]] = None
    project: str = Field(default="triage-governance", max_length=128)
    run_name: Optional[str] = Field(default="governance-policy-checks", max_length=128)
    mode: str = "online"

    @field_validator("mode")
    @classmethod
    def _mode_allowed(cls, v: str) -> str:
        mode = (v or "").strip().lower()
        if mode not in {"online", "offline"}:
            raise ValueError("mode must be 'online' or 'offline'")
        return mode


@router.get(
    "/governance/wandb-status",
    dependencies=[Depends(requires(authz.PERM_VIEW_AUDIT_LOG, "governance_wandb_status"))],
)
def governance_wandb_status():
    """Report non-secret backend W&B readiness for the Streamlit UI."""
    from app.governance.wandb_logging import wandb_available, wandb_configured
    from app.security.identity import (
        cloud_egress_allowed,
        local_credentialed_research_mode,
        patient_data_mode,
    )

    local_mode = local_credentialed_research_mode()
    available = wandb_available()
    configured = wandb_configured()
    return {
        "available": available,
        "configured_for_online": configured,
        "cloud_egress_allowed": cloud_egress_allowed(),
        "local_credentialed_research": local_mode,
        "patient_data_mode": patient_data_mode(),
        "offline_allowed_in_local_research": (
            not local_mode
            or __import__("os").environ.get("ALLOW_WANDB_OFFLINE_IN_LOCAL_RESEARCH", "").lower() == "true"
        ),
        "status": (
            "configured"
            if configured
            else "available_not_configured"
            if available
            else "not_installed"
        ),
    }


@router.post(
    "/governance/log-wandb",
    dependencies=[Depends(requires(authz.PERM_VIEW_AUDIT_LOG, "governance_log_wandb"))],
)
def governance_log_wandb(body: WandbLogRequest):
    """Perform optional W&B logging on the backend behind RBAC/audit."""
    from app.governance.wandb_logging import log_governance_run

    return log_governance_run(
        body.project,
        body.policy_results,
        body.red_team_results,
        body.model_metrics,
        run_name=body.run_name,
        mode=body.mode,
    )
