"""
Fixture-only AutoGen clinician-chat helper.

The public app/API does not call this raw-stay_id helper. The live explanation
surface is POST /cases/{case_uid}/explanations, which resolves a pseudonymous
case_uid on the backend. This module is retained for explicit fixture-based
tests and offline experiments only.

DESIGN PRINCIPLE -- READ BEFORE EDITING
========================================
AutoGen is used here for ORCHESTRATION and EXPLANATION ONLY. It is never
given authority over a clinical decision. Concretely:

  - The actual triage decision (Manchester engine), the safety review, the
    leakage guard, and the ML prediction are 100% unchanged, deterministic
    Python, exactly as already reviewed and tested elsewhere in this project.
  - The AutoGen agent's only tool is `get_verified_evidence_for_stay`, which
    internally calls the existing `run_workflow()` orchestrator. The agent
    receives a plain dict of already-computed, already-safe evidence. It
    cannot invent a vital sign, a triage category, or a risk number, because
    none of those values are ever generated by the LLM -- they are looked up.
  - Every reply from the agent is re-validated by a deterministic safety
    filter (`_validate_chat_reply_safety`, in this file) built on the SAME
    shared forbidden-phrase check (`app/rules/llm_safety_filter.py`) already
    used by `llm_explanation_agent.py`, so the two LLM-facing surfaces in
    this project cannot silently diverge on what counts as a forbidden
    phrase. The chat-specific check adds one conversation-appropriate
    completeness requirement (must mention human/clinical review) without
    the explanation agent's stricter five-section completeness checks,
    which would misfire on short factual chat answers (see
    app/rules/llm_safety_filter.py docstring for the full reasoning).
  - If Azure OpenAI is not configured, this module degrades gracefully and
    says so. It never crashes the rest of the application.

If you are tempted to give the agent a tool that lets it set a triage
category, change a vital sign, or skip the safety filter: stop. That would
reverse the entire point of this design.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Optional

from dotenv import load_dotenv

from app.schemas.internal import EDTriageCase
from app.agents.orchestrator import run_workflow
from app.rules.llm_safety_filter import check_forbidden_phrases
from app.storage.jsonl_repository import read_jsonl


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ENV_PATH = PROJECT_ROOT / ".env"


CHAT_SYSTEM_MESSAGE = """\
You are the Clinician Chat Agent for a research prototype AI triage system.

This system is NOT for clinical use. It is a research prototype only.

You have exactly one tool: get_verified_evidence_for_stay(stay_id). Use it to
look up the verified evidence for the case the clinician is asking about.
Do not answer questions about a case before calling this tool for that
stay_id at least once in the conversation.

STRICT RULES -- you must follow these without exception:

1. Only discuss the verified evidence returned by your tool. Never invent
   vital signs, symptoms, risk factors, or clinical facts.
2. Do NOT create, assign, infer, or change a Manchester Triage System category
   yourself. You MAY restate a provisional category the deterministic engine
   already produced, but you must always label it provisional, unvalidated, not
   the official MTS, and not clinically approved.
3. Do NOT diagnose the patient.
4. Do NOT recommend treatment, medication, or procedures.
5. Do NOT recommend admission, discharge, or any other disposition.
6. Do NOT map or convert any external/non-MTS triage scale to Manchester.
7. Always state that human clinical review is required before any action.
8. If asked about something not present in the verified evidence, say so
   plainly rather than guessing.
9. If asked to make a clinical decision, explain clearly that you cannot do
   this and that a clinician must decide.

You may:
  - Explain what the verified evidence shows, in plain language.
  - Explain what vital sign values mean in general clinical context.
  - Explain why the deterministic safety rules engine reached its output.
  - Explain what data is missing and why that matters.
  - Summarise the case for a clinician who has not yet read it.
"""


def _build_evidence_dict(case: EDTriageCase) -> dict[str, Any]:
    """
    Run the existing, already-tested deterministic workflow and return a
    plain dict of verified evidence. This is the ONLY source of facts the
    chat agent is given about a case.
    """
    result = run_workflow(case, include_llm_explanation=False)
    return {
        "stay_id": result.stay_id,
        "source_dataset": case.source_dataset,
        "chief_complaint": result.triage_input.chiefcomplaint,
        "age": result.triage_input.age,
        "gender": result.triage_input.gender,
        "arrival_transport": result.triage_input.arrival_transport,
        "triage_vitals": {
            "temperature": result.triage_input.temperature,
            "temperature_unit": result.triage_input.temperature_unit,
            "heartrate": result.triage_input.heartrate,
            "resprate": result.triage_input.resprate,
            "o2sat": result.triage_input.o2sat,
            "sbp": result.triage_input.sbp,
            "dbp": result.triage_input.dbp,
            "nrs_pain": result.triage_input.nrs_pain,
            "pain_present": result.triage_input.pain_present,
        },
        "data_validation_status": result.data_validation.validation_status,
        "missing_fields": (
            result.data_validation.missing_required_fields
            + result.data_validation.non_informative_fields
        ),
        "rules_engine_status": result.decision.classification_status,
        "rules_engine_reason_codes": result.decision.reason_codes,
        "rules_engine_note": (
            "No clinician-APPROVED Manchester category is assigned. If a "
            "category is present, it was produced by a PROVISIONAL, unvalidated "
            "research ruleset (not the official Manchester Triage System) and "
            "requires clinician confirmation. The source dataset is "
            f"{case.source_dataset}, which is not itself Manchester-labelled."
        ),
        "safety_flags": result.safety_review.data_quality_flags,
        "is_safe_to_present": result.safety_review.is_safe_to_present,
        "ml_research_estimate": {
            "available": result.ml_prediction.prediction_available,
            "prediction_scale": result.ml_prediction.prediction_scale,
            # Retired compatibility fields are never populated by the full-MIMIC path.
            "predicted_ktas_class": result.ml_prediction.predicted_ktas_class,
            "emergency_research_estimate": result.ml_prediction.emergency_research_estimate,
            # MIMIC acuity fields (populated only for MIMIC cases)
            "predicted_mimic_acuity": result.ml_prediction.predicted_mimic_acuity,
            "mapped_mts_category": result.ml_prediction.mapped_mts_category,
            "mapped_mts_priority": result.ml_prediction.mapped_mts_priority,
            "mapped_mts_max_wait_minutes": result.ml_prediction.mapped_mts_max_wait_minutes,
            "model_note": result.ml_prediction.model_note,
        },
        "final_acuity_assessment": {
            "applicable": result.final_acuity_assessment.applicable,
            "final_acuity": result.final_acuity_assessment.final_acuity,
            "category": result.final_acuity_assessment.category,
            "override_applied": result.final_acuity_assessment.override_applied,
            "override_tier": result.final_acuity_assessment.override_tier,
            "override_note": result.final_acuity_assessment.override_note,
        },
        "policy": (
            "Research prototype. Not for clinical use. For MIMIC cases the ML "
            "model predicts ESI acuity, mapped to an MTS-style display category; "
            "an escalate-only vital override may raise it. Retired non-full-MIMIC "
            "models are never substituted. Any category is provisional and "
            "unvalidated. Human clinical review is required before any action "
            "on this case."
        ),
    }


def _make_evidence_tool(cases_path: Path):
    """
    Builds the get_verified_evidence_for_stay tool, closed over a specific
    cases file path so the tool signature exposed to the LLM stays a single
    plain integer argument.
    """

    def get_verified_evidence_for_stay(stay_id: int) -> dict:
        """Look up verified triage-time evidence for one ED stay by its stay_id."""
        records = read_jsonl(cases_path)
        matches = [r for r in records if int(r.get("stay_id", -1)) == stay_id]
        if not matches:
            return {
                "error": f"No case found with stay_id={stay_id}.",
                "available_stay_ids_sample": [int(r["stay_id"]) for r in records[:10]],
            }
        case = EDTriageCase(**matches[0])
        return _build_evidence_dict(case)

    return get_verified_evidence_for_stay


def load_azure_config() -> Optional[dict]:
    """Returns Azure OpenAI config dict, or None if not configured OR if cloud
    egress is disabled for the active profile. In the LOCAL_CREDENTIALED_RESEARCH
    profile, cloud egress is OFF by default (no patient-derived data leaves the
    box) unless ALLOW_CLOUD_LLM_IN_LOCAL_RESEARCH=true and
    APPROVED_CLOUD_LLM_DATA_PROCESSING=true are both set after documented
    zero-retention/no-training/no-human-review approval."""
    from app.security.identity import cloud_egress_allowed
    if not cloud_egress_allowed():
        return None
    load_dotenv(dotenv_path=ENV_PATH)
    required = [
        "AZURE_OPENAI_ENDPOINT", "AZURE_OPENAI_API_KEY",
        "AZURE_OPENAI_DEPLOYMENT", "AZURE_OPENAI_API_VERSION",
    ]
    if any(not os.getenv(k) for k in required):
        return None
    return {
        "endpoint": os.environ["AZURE_OPENAI_ENDPOINT"],
        "api_key": os.environ["AZURE_OPENAI_API_KEY"],
        "deployment": os.environ["AZURE_OPENAI_DEPLOYMENT"],
        "api_version": os.environ["AZURE_OPENAI_API_VERSION"],
        "model": os.environ.get("AZURE_OPENAI_MODEL", os.environ["AZURE_OPENAI_DEPLOYMENT"]),
    }


def build_model_client(config: dict):
    """
    Builds the real Azure OpenAI model client for AutoGen.

    model_info is supplied explicitly rather than left to name-based
    detection, because Azure deployment names are often custom and should
    not silently change the model's assumed capabilities.
    """
    from autogen_ext.models.openai import AzureOpenAIChatCompletionClient
    from autogen_core.models import ModelInfo

    model_info = ModelInfo(
        vision=False,
        function_calling=True,
        json_output=False,
        family="unknown",
        structured_output=False,
    )
    return AzureOpenAIChatCompletionClient(
        model=config["model"],
        azure_endpoint=config["endpoint"],
        azure_deployment=config["deployment"],
        api_version=config["api_version"],
        api_key=config["api_key"],
        model_info=model_info,
    )


def build_chat_agent(model_client, cases_path: Path):
    """
    Builds the AssistantAgent. Exposed separately from run_chat_turn so tests
    can inject a ReplayChatCompletionClient instead of a real Azure client.
    """
    from autogen_agentchat.agents import AssistantAgent

    return AssistantAgent(
        name="clinician_chat_agent",
        model_client=model_client,
        tools=[_make_evidence_tool(cases_path)],
        system_message=CHAT_SYSTEM_MESSAGE,
        reflect_on_tool_use=True,
        max_tool_iterations=3,
    )


def _validate_chat_reply_safety(text: str) -> list[str]:
    """
    Safety check for a single conversational chat reply.

    Uses the shared forbidden-phrase check (same blocked phrases as the
    single-shot LLM Explanation Agent, so the two surfaces cannot silently
    diverge on what counts as dangerous). Adds exactly one completeness
    requirement on top: the reply must reference human/clinical review.
    Deliberately does NOT require every reply to restate "no category
    assigned" or "data is missing" the way the explanation agent's mandated
    five-section format does -- a short factual answer to "what's the heart
    rate?" has no occasion to say either of those things, and requiring it
    would make this flag fire constantly on safe answers, training people to
    ignore it.
    """
    failures = check_forbidden_phrases(text)
    lower = text.lower()
    if "human review" not in lower and "clinical review" not in lower and "clinician" not in lower:
        failures.append("MISSING_HUMAN_REVIEW_REQUIREMENT")
    return failures


async def run_chat_turn(
    agent,
    question: str,
) -> dict:
    """
    Runs one user turn through the agent and applies the deterministic
    safety filter to the final reply, exactly mirroring the PASS/SAFETY_FAIL
    pattern already used in llm_explanation_agent.py. Returns a plain dict
    rather than raising, so callers (the API, the frontend) never need to
    catch agent-internal exceptions to get a usable result.
    """
    try:
        result = await agent.run(task=question)
    except Exception as exc:
        return {
            "status": "ERROR",
            "reply_text": (
                f"Chat agent failed: {type(exc).__name__}. "
                "Human clinical review of the verified evidence is still required."
            ),
            "safety_failures": [f"AGENT_CALL_FAILED: {type(exc).__name__}"],
        }

    final_text = ""
    for msg in reversed(result.messages):
        content = getattr(msg, "content", None)
        if isinstance(content, str) and content.strip():
            final_text = content
            break

    safety_failures = _validate_chat_reply_safety(final_text) if final_text else [
        "EMPTY_RESPONSE"
    ]
    return {
        "status": "PASS" if not safety_failures else "SAFETY_FAIL",
        "reply_text": final_text,
        "safety_failures": safety_failures,
    }


async def run_single_question(
    question: str,
    cases_path: Optional[Path] = None,
) -> dict:
    """
    Convenience entry point for a single, stateless question -- builds a
    fresh agent, asks one question, returns the filtered result. This legacy
    raw-stay_id helper is retained for explicit tests/fixtures only; the public
    API uses /cases/{case_uid}/explanations.

    Returns a dict with status NOT_CONFIGURED if Azure OpenAI credentials are
    absent, rather than raising, matching the existing degrade-gracefully
    pattern used throughout this project's LLM-facing code.
    """
    config = load_azure_config()
    if config is None:
        return {
            "status": "NOT_CONFIGURED",
            "reply_text": (
                "Azure OpenAI is not configured. Set AZURE_OPENAI_ENDPOINT, "
                "AZURE_OPENAI_API_KEY, AZURE_OPENAI_DEPLOYMENT, and "
                "AZURE_OPENAI_API_VERSION in .env to enable the chat agent. "
                "Human clinical review of the verified evidence is still required."
            ),
            "safety_failures": [],
        }

    if cases_path is None:
        return {
            "status": "ERROR",
            "reply_text": (
                "No explicit case evidence source was provided for the legacy "
                "raw-stay_id chat helper. Use the case_uid-keyed explanation "
                "API for app usage. Human clinical review is still required."
            ),
            "safety_failures": ["NO_EXPLICIT_CASE_SOURCE"],
        }

    model_client = build_model_client(config)
    agent = build_chat_agent(model_client, cases_path)
    try:
        return await run_chat_turn(agent, question)
    finally:
        await model_client.close()
