"""
DEPRECATED — DO NOT USE FOR TRAINING.

This script has been superseded by scripts/build_outcome_labels.py.

REASON FOR DEPRECATION
=======================
The proxy MTS labels generated by this script had two critical problems:

1. CIRCULAR LABEL PROBLEM
   The generated labels were driven 55% by the MIMIC acuity field.
   Training a model on those labels then predicting acuity means the model
   is simply re-learning the MIMIC acuity field — not patient physiology.

2. MISSING VITAL SIGNS
   The output mts_labels.jsonl contained no vital sign features.
   Every feature in the training matrix was -1.0 (the missing sentinel).
   The model learned nothing from physiology.

CORRECT REPLACEMENT
===================
Use scripts/build_outcome_labels.py instead.

That script joins triage-time vitals with real MIMIC outcome labels:
  - label_admitted: was the patient admitted to hospital?
  - label_high_acuity: was MIMIC acuity 1 or 2?

These are real MIMIC-IV-ED outcomes, not invented proxy categories.
They are consistent with Section 7 of the project outline:
  "Train baseline models for hospital admission, ICU transfer,
   mortality risk, deterioration risk, or ED disposition."

Run:
  python scripts/build_outcome_labels.py
  python ml_training/train_all_models.py
"""
import sys

print("=" * 70)
print("ERROR: generate_mts_labels.py is DEPRECATED.")
print()
print("This script generated unsafe proxy MTS labels with no vital sign")
print("features and a circular dependency on the MIMIC acuity field.")
print()
print("Use the replacement instead:")
print("  python scripts/build_outcome_labels.py")
print("  python ml_training/train_all_models.py")
print("=" * 70)
sys.exit(1)
